import { library } from "@fortawesome/fontawesome-svg-core";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faGear,
  faDiagramProject,
  faGraduationCap,
  faSearch,
  faDollarSign,
  faCode,
  faUser as faUserSolid,
  faSpinner,
  faCheck,
  faCheckCircle,
  faXmarkCircle,
  faServer,
  faStar,
  faPhone,
  faCodeCommit,
  faAnglesUp,
  faFileCsv,
  faDownload,
  faXmark,
  faCircleInfo,
} from "@fortawesome/free-solid-svg-icons";

import {
  faChartBar,
  faUser,
  faCircleUser,
  faFile,
  faCreditCard,
  faBell,
  faRectangleList,
  faCircleCheck,
  faRectangleXmark,
  faTrashCan,
  faHeart,
  faComments,
  faEnvelope,
  faFaceSmile,
  faNewspaper,
  faFilePdf,
  faImages,
  faFileWord,
} from "@fortawesome/free-regular-svg-icons";

import {
  faTwitter,
  faFacebookF,
  faYoutube,
  faLinkedin,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faChartBar,
  faGear,
  faUser,
  faDiagramProject,
  faGraduationCap,
  faCircleUser,
  faFile,
  faCreditCard,
  faSearch,
  faBell,
  faDollarSign,
  faCode,
  faUserSolid,
  faRectangleList,
  faSpinner,
  faCheck,
  faCircleCheck,
  faRectangleXmark,
  faTrashCan,
  faHeart,
  faComments,
  faTwitter,
  faFacebookF,
  faYoutube,
  faLinkedin,
  faCheckCircle,
  faXmarkCircle,
  faServer,
  faStar,
  faPhone,
  faEnvelope,
  faFaceSmile,
  faNewspaper,
  faCodeCommit,
  faFilePdf,
  faAnglesUp,
  faFileCsv,
  faImages,
  faFileWord,
  faDownload,
  faXmark,
  faCircleInfo
);

export default FontAwesomeIcon;
